### ISSUE TITLE
"Error while setting up tgtg platform for sensor" and sensors are unavailables

### ISSUE THREAD

**Issue by Chouffy** [Chouffy/home_assistant_tgtg#1]
TooGoodToGo change their authentication method.
We have to wait for [upstream module](https://github.com/ahivert/tgtg-python/issues/119) to be corrected.
Also good to watch the progress on the [node-js module](https://github.com/marklagendijk/node-toogoodtogo-watcher/issues/112)

**Comment by FeikoJoosten** [comment]
@Chouffy the node-js module just posted a fix!

**Comment by Chouffy** [comment]
@FeikoJoosten Indeed! But in the upstream module I use, things are not yet corrected :(
I'll try to have a look to see how we can fix that, maybe with the help of [this PR](https://github.com/ahivert/tgtg-python/pull/114)
Only after the python module works I can adapt it to Home Assistant

**Comment by Chouffy** [comment]
Fixed in release 2.0.2 by [this commit](https://github.com/Chouffy/home_assistant_tgtg/commit/0da1e3d39d035dbfb0b1fe8dee3204ed093d7b02) :)
