### ISSUE TITLE
Captcha - you have been blocked

### ISSUE THREAD

**Issue by jjmwiwi** [Chouffy/home_assistant_tgtg#129]
### System Health details

It seems, that tgtg has been blocked my requests to list my favorites and items. It links to https://geo.captcha-delivery.com/captcha/?initialCid.... which says: you have been blocked
<img width="332" alt="Screenshot 2024-08-04 204501" src="https://github.com/user-attachments/assets/67051f84-ccc8-468e-bd44-96021629c885">

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/Chouffy/home_assistant_tgtg/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

you have been blocked

### Reproduction steps

1.    ./tgtg_get_favorites_item_id.py
2. 
3.
...

### Debug logs

```text
Press enter to continue ...
Traceback (most recent call last):
  File "./tgtg_get_favorites_item_id.py", line 14, in <module>
    tgtgReply = tgtgClient.get_items()
  File "/home/.local/lib/python3.8/site-packages/tgtg/__init__.py", line 274, in get_items
    raise TgtgAPIError(response.status_code, response.content)
tgtg.exceptions.TgtgAPIError: (403, b'{"url":"https://geo.captcha-delivery.com/captcha/?initialCid=....
```

**Comment by lampje25** [comment]
Exactly the same problem here!

**Comment by jeje-digifab** [comment]
Hello,
Same problem

```python
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 361, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tgtg/sensor.py", line 83, in setup_platform
    tgtgReply = tgtg_client.get_items()
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/tgtg/__init__.py", line 244, in get_items
    self.login()
  File "/usr/local/lib/python3.12/site-packages/tgtg/__init__.py", line 153, in login
    self._refresh_token()
  File "/usr/local/lib/python3.12/site-packages/tgtg/__init__.py", line 139, in _refresh_token
    raise TgtgAPIError(response.status_code, response.content)
tgtg.exceptions.TgtgAPIError: (403, b'{"url":"https://geo.captcha-delivery.com/captcha/?initialCid=
```

**Comment by sebsst** [comment]
Hello
same here, I created a new account so I'm no longer blockedcand put scan_interval to 10000 so it's not getting refreshed (almost). Then I would like to refresh my favorites only during some hours/ days to avoid to be blocked again.
Is it possible with existing integration? 
For example I could have an automation for that, but home assistant action "update entity" doesn't seem to work.
Any idea how to achieve this?

thanks

**Comment by euro2** [comment]
same. They rate limited the api i think?

**Comment by jlssmt** [comment]
same problem here

**Comment by tjorim** [comment]
Out of our control, nothing we can do about it. I assume tgtg is locking things down. We rely on an upstream python library which already has this issue reported. https://github.com/ahivert/tgtg-python/issues/321 The only thing you can try is generating new cookies/tokens and making sure polling rate is not too high.
