### ISSUE TITLE
URL of the shop image

### ISSUE THREAD

**Issue by poudenes** [Chouffy/home_assistant_tgtg#133]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/Chouffy/home_assistant_tgtg/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

no problem ate all

### Describe the solution you'd like

A other integration based on MQTT have option to load the img of the shop. Its a URL directly to the image

### Describe alternatives you've considered

I don't know

### Additional context

would be nice to have this option. Then you can send notifications with a nice logo :)

**Comment by tjorim** [comment]
Changes are present in version 5.6.0 (currently released as beta): https://github.com/Chouffy/home_assistant_tgtg/releases/tag/5.6.0
