### ISSUE TITLE
Favourites missing after restart

### ISSUE THREAD

**Issue by BNoiZe** [Chouffy/home_assistant_tgtg#23]
Hello,
thank you for your work on this integration!
I have the problem, that I add new favourites in the TGTG-app and after a restart they are not showing up. They are even missing if I check the favourites using the python script.

**Comment by BNoiZe** [comment]
Logging in works flawlessly. With the python script there is no error displayed. Also no error in the logs.

**Comment by Chouffy** [comment]
@BNoiZe Just to be sure, when you says "python script", you refer to [this one that get favorites](https://github.com/Chouffy/home_assistant_tgtg/blob/main/tgtg_get_favorites_item_id.py) right?

If that so, there's nothing that I can do as the script just call the upstream module [tgtg-python](https://github.com/ahivert/tgtg-python). Could you please create an issue in the module repository? I'll close this one for now.
