### ISSUE TITLE
[New feature] Get active orders with pick-up window

### ISSUE THREAD

**Issue by Rikkie80** [Chouffy/home_assistant_tgtg#26]
Would be nice to have a (binary) sensor to track what you ordered and also the pick up window for your order(s). In this way you can automate HA to warn e.g. when it's time to pick up the order.

**Comment by Chouffy** [comment]
Hey @Rikkie80 , thanks for your suggestion!
It seems that the upstream module used [implement this feature](https://github.com/ahivert/tgtg-python#get-an-item=), so it could be integrated into Home Assistant.
However I currently lack the time to do it ... I'll left this open if anyone can/want to pick it up.

**Comment by EvertJob** [comment]
Yes, this would be nice!

**Comment by chris24walsh** [comment]
https://github.com/Chouffy/home_assistant_tgtg/pull/95

**Comment by tjorim** [comment]
Please try out https://github.com/Chouffy/home_assistant_tgtg/releases/tag/5.4.0.
It's currently in beta but can be downloaded with HACS.
Will probably publish to stable in a week if no issues pop up.
