### ISSUE TITLE
Please change tgtg version

### ISSUE THREAD

**Issue by maartenhendrix** [Chouffy/home_assistant_tgtg#27]
Please change version to 0.11.2
https://github.com/Chouffy/home_assistant_tgtg/blob/5fd42974afdec7e7caab422e6463822eb075a471/custom_components/tgtg/manifest.json#L8

**Comment by Chouffy** [comment]
Done and [published with release 4.0.2](https://github.com/Chouffy/home_assistant_tgtg/releases/tag/4.0.2)! Thanks @maartenhendrix 😊

**Comment by maartenhendrix** [comment]
@Chouffy there is a new version again 😬 0.11.3

**Comment by Chouffy** [comment]
@maartenhendrix well, 0.11.2 was a short lived one! 😁 It's updated :)

**Comment by Chouffy** [comment]
@maartenhendrix would you be interested to have write access to this repo to do this kind of updates?
I may be not available sometime, so it would be great to have a 2nd person that can do it, and I see that you follow tgtg updates 😊

**Comment by maartenhendrix** [comment]
Yeah i was trying to make a pull request but was not allowed. So would be nice.

**Comment by Chouffy** [comment]
OK I'm not experienced in this, but I've tried to add you as a maintainer.

Note that after bumping the dependency [like here](https://github.com/Chouffy/home_assistant_tgtg/commit/de605ee9b1b2f10f6d21ac494f92af9ef525c95a), a new release needs to be done [here](https://github.com/Chouffy/home_assistant_tgtg/releases)

So let me know if you need me to do something from my side😊

**Comment by maartenhendrix** [comment]
Okay thanks I’ll give it a try
