### ISSUE TITLE
Favorites limited to 25?

### ISSUE THREAD

**Issue by DYLaKo** [Chouffy/home_assistant_tgtg#29]
Hi,

I implemented your component yesterday, looks great. When I showed my wife, she added some more favorites to our TooGoodToGo app, which now has about 35 favorites (it was like 22). 

After a reboot of HomeAssistant I see that some previous working sensors are now gone, and the amount of working sensors is 25. It looks like a hard limit, and by adding more than 25 favorites, some existing disappeared and some new do not show up. 

Is the limit 25? If yes, is it possible to increase the limit?

**Comment by Chouffy** [comment]
Hi @DYLaKo ,

I didn't coded any hard limit and I didn't tested the integration with more than 15 favorites to be honest.
Could you try to use the [upstream tgtg module](https://github.com/ahivert/tgtg-python) from your PC directly?
So we can pin-point if the issue is on the Home Assistant side of things, or on the `tgtg` module :)

**Comment by ahivert** [comment]
the default page_size setted in tgtg package is 20 => https://github.com/ahivert/tgtg-python/blob/master/tgtg/__init__.py#L213

**Comment by Chouffy** [comment]
> the default page_size setted in tgtg package is 20 => https://github.com/ahivert/tgtg-python/blob/master/tgtg/__init__.py#L213

Could we make it configurable when the `TgtgClient` is built? so then I can expose this configuration in Home Assistant
That could be something like `client = TgtgClient(email="<your_email>", page_size=50)

**Comment by tjorim** [comment]
Will be implemented with v6.

**Comment by Guillaumer2h** [comment]
Hello, thank you for your work! When will the v6 be available? Having more favourites would be great ! Thanks !
