### ISSUE TITLE
[Need Help] Use Home Assistant UI to set-up TGTG integration and import tokens

### ISSUE THREAD

**Issue by Chouffy** [Chouffy/home_assistant_tgtg#3]
Goal:
* Use Home Assistant UI to set up the integration
* Be able to store somewhere the token generated when a username/password is used

Unfortunately I lack skill or time to do it, so I would be glad if somebody can help me on that!

**Comment by tjorim** [comment]
Implemented: https://github.com/Chouffy/home_assistant_tgtg/pull/67
