### ISSUE TITLE
Component does not run

### ISSUE THREAD

**Issue by seymourd** [Chouffy/home_assistant_tgtg#32]
Hello,

First of all, thank you for the good work you've been doing with the integration !

I installed the latest update to solve the 403 error I've been having for months, but the integration doesn't seem to launch.
I renewed my tokens using the script and updated the config accordingly, but it doesn't work even after several reboots.
I have nothing in the system journal, no tgtg entities.

Am I missing something ?

**Comment by Chouffy** [comment]
Hey @seymourd 

Thanks for the nice words 😊
It surprising that there's no words in the log about it.
Normally, if you go to Settings -> System -> Logs -> Full Logs, do you have at least something like below?
This would show that the component is loading. Is there is something afterward?

```
[...] WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration tgtg which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
```

**Comment by seymourd** [comment]
I've got favorites in my account, I tried 2 different accounts, each time without any additionnal settings and with (valid) store IDs added manually.
No entity is generated :(

**Comment by Chouffy** [comment]
Can you share your `configuration.yaml` for the `tgtg` section?
Hide your secrets keys of course :)

**Comment by seymourd** [comment]
Sure, it's the plain output from the python script:
```
sensor:
  - platform: tgtg
    username: 'xxx@gmail.com'
    access_token: 'e30.xxxx'
    refresh_token: 'e30.xxxx'
    user_id: '4xxxxxx1'
    scan_interval: 900
```

That's it.

I also tried updating HA, HACS, tgtg, home_assistant_tgtg, all to the latest version, de downloading ha_tgtg through HACS, all without success :(

**Comment by Chouffy** [comment]
🤔 I really have no idea ... maybe could you try to configure your tgtg in a new Home Assistant environment? So we can be sure it's related to TGTG and not your Home Assistant installation
You can set up a development one using [this guide](https://developers.home-assistant.io/docs/development_environment/)

**Comment by seymourd** [comment]
Hello @Chouffy,

After several tries, backups restores, ect, I eventually found out :
The issue was a wrong configuration on my end, not related to the module at all.
FYI, I had defined several `sensor:` entries, leading to some HA internal trouble, even though the config passed the validator successfully...
Sorry for the trouble, and again thank you !
