### ISSUE TITLE
Docker container for tgtg_get_tokens

### ISSUE THREAD

**Issue by DavidDeSloovere** [Chouffy/home_assistant_tgtg#33]
Would be great if we could just run a docker command to fire this up.
I will probably try this for myself. If I get anywhere I can post the docker file.
You would need build scripts to create the image, copy the tgtg_get_tokens script and upload to docker hub (or github packages).

**Comment by Chouffy** [comment]
Hey @DavidDeSloovere thanks for your input!
That would be a very good idea, however I don't have a lot of experience in docker files.
If have the skills and time to do it, I would be more than happy to merge or reference it here!

**Comment by Chouffy** [comment]
An even better solution would be to manage everything from the Home-Assistant UI (see #3), but I won't have the skill & time to do it.

**Comment by DavidDeSloovere** [comment]
I saw the #3 but I'm guessing the effort for that one would be bigger. I'll see what I can come up with for the docker route.

**Comment by DavidDeSloovere** [comment]
https://github.com/Chouffy/home_assistant_tgtg/pull/35
