### ISSUE TITLE
403 error - Please enable JS and disable any ad blocker

### ISSUE THREAD

**Issue by AdamorfuX** [Chouffy/home_assistant_tgtg#37]
Integration of tgtg is not working on my setup.

In the logs i see error 403, it responds with geo.captcha-delivery.com

Any ideas?

**Comment by AdamorfuX** [comment]
I tried different agent ID, but no budge. I must have messed something up

**Comment by pbertra** [comment]
Same issue here
Everything was working fine up to a few days ago

**Comment by miit86** [comment]
same error.

1 request in 10 minutes.
app is working OK from same IP adres.

so the plugins missings something.?

**Comment by Tiggel** [comment]
Same issue here..I can make requests from the same machine where HA is installed on. But in HA I get the above mentioned exception

**Comment by Chouffy** [comment]
Hi all,
I'll reopen this issue, I'm also facing it myself.
There's not so much I can do in this module, as it's fully dependent on the [`tgtg-python` library](https://github.com/ahivert/tgtg-python)
There's already [an active issue](https://github.com/ahivert/tgtg-python/issues/205) on their side so no need to create another one here or there :)
Hopefully we can find something!

**Comment by sepodele** [comment]
Apparently it's fixed at the tgtg-python library now. Can you bump to newest version? :)

**Comment by Alfagek** [comment]
@tjorim fix is working great. Manual update Tgtg and import file. Did a new validation, and it’s working flawlessly

**Comment by lampje25** [comment]
Working good after update files
