### ISSUE TITLE
Sensors show as unavailable 

### ISSUE THREAD

**Issue by djoaza** [Chouffy/home_assistant_tgtg#44]
Hello
Some time ago sensor.tgtg became inaccessible.
There was this error in the logs
![image](https://user-images.githubusercontent.com/73444368/206862717-71e2a346-36b8-40a1-aa69-cec499bc0e32.png)
How can I fix this error?

**Comment by Chouffy** [comment]
Hi,
As the message suggest, your token may be outated. 
Try to get new ones with the [script](https://github.com/Chouffy/home_assistant_tgtg/blob/main/tgtg_get_tokens.py) and update your config file

**Comment by djoaza** [comment]
> Hi, As the message suggest, your token may be outated. Try to get new ones with the [script](https://github.com/Chouffy/home_assistant_tgtg/blob/main/tgtg_get_tokens.py) and update your config file

Thanks a lot it worked
