### ISSUE TITLE
problem just after installing Home Assistant 2023.1.2

### ISSUE THREAD

**Issue by gitioda** [Chouffy/home_assistant_tgtg#46]
Hello,
i just updated my HA from the last 2022 version directly to the 2023.1.2
since then, in the UI, all my TGTG are "not available"  => it seems related to the new HA release (?)
i joined the logged error
Thanks in advance for your help :-)

************************************************

Home Assistant 2023.1.2
Supervisor 2022.12.1
Operating System 9.4
Interface utilisateur : 20230104.0 - latest
**************************************************

Détails du journal (ERREUR)
Logger: homeassistant.components.sensor
Source: custom_components/tgtg/sensor.py:75
Integration: Capteur ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 06:19:55 (1 occurrences)
Last logged: 06:19:55

Error while setting up tgtg platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 289, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/tgtg/sensor.py", line 75, in setup_platform
    tgtgReply = tgtg_client.get_items()
  File "/usr/local/lib/python3.10/site-packages/tgtg/__init__.py", line 229, in get_items
    self.login()
  File "/usr/local/lib/python3.10/site-packages/tgtg/__init__.py", line 139, in login
    self._refresh_token()
  File "/usr/local/lib/python3.10/site-packages/tgtg/__init__.py", line 129, in _refresh_token
    raise TgtgAPIError(response.status_code, response.content)
tgtg.exceptions.TgtgAPIError: (401, b'{"errors":[{"code":"UNAUTHORIZED","message":"Invalid token for: SoteriaRenewTokenRequest(clientIp=85.201.162.62, clientUserAgent=TGTG/22.12.1 Dalvik/2.1.0 (Linux; U; Android 10; SM-G935F Build/NRD90M), initiatedByUserId=null, permissions=0,5,12411195,0)"}]}')

**Comment by Chouffy** [comment]
Hey @gitioda 
Good idea that you've put the log, as the answer is in it 😊 Your token may be outated.
Try to get new ones with the [script](https://github.com/Chouffy/home_assistant_tgtg/blob/main/tgtg_get_tokens.py) and update your config file!

**Comment by gitioda** [comment]
Thanks a lot Chouffy ! 
works now
seems necessary to update tokens every year ...
  👍
