### ISSUE TITLE
Unable to get this working

### ISSUE THREAD

**Issue by joeinertia** [Chouffy/home_assistant_tgtg#50]
Hi guys, HA nooby here, I have the component installed via HACS, i've added to my configuration.yarl after running the py scripts etc..

I've added a custom sensor before and been fine, but for some reason I can't seem to get this one going - I get nothing in HA at all, no entitity or sensor at all - i've done the custom ID's etc, just wondering if there's anything obvious i'm missing? 

I'm running HA via Truenas Scale - all files are downloaded in the custom component folder seemingly fine.

**Comment by Chouffy** [comment]
Hi! Welcome here 😊
What kind of error do you have? could you attach the logs from Home Assistant?
There's an on-going 403 issue for most users … so maybe that's what you have  - see #37

**Comment by Chouffy** [comment]
Hi @joeinertia, I'll close this one as a new release has been pushed. Maybe this will solve your issue!
