### ISSUE TITLE
Cookies attribute missing

### ISSUE THREAD

**Issue by Rikkie80** [Chouffy/home_assistant_tgtg#55]
Tried to re-activate my (Dutch) TGTG integration, but ran into this issue:
`
Traceback (most recent call last):
  File "/home/esilverentand/tgtg_get_tokens.py", line 25, in <module>
    print("    cookie: '" + tgtgClient.cookie + "'")
AttributeError: 'TgtgClient' object has no attribute 'cookie'
`
Downloaded the latest version of tgtg_get_tokens.py
Other data is found by the script

**Comment by Rikkie80** [comment]
Never mind. Had to "pip install" tgtg to 0.14.0 as well

**Comment by Chouffy** [comment]
No worries - I've added a line in the release read me :)

**Comment by Rikkie80** [comment]
Ok, then for completeness also mention that the latest tgtg_get_tokens.py must be used 😉
