### ISSUE TITLE
Price in attributes: 0 missing

### ISSUE THREAD

**Issue by Rikkie80** [Chouffy/home_assistant_tgtg#57]
As the TGTG price and Original value in the sensor attributes are no clean numbers, I cannot add a 0 to it (e.g. when the price is 10,50 EUR, the result is 10.5 EUR). I would like to have the 2nd digit behind the comma added, or to make it a clean number so that I can do it myself in my automation.

Item ID: 523323
Item URL: https://share.toogoodtogo.com/item/523323
TGTG Price: **3.5 EUR**
Original value: **10.5 EUR**
Pickup start: 2023-02-02T19:00:00Z
Pickup stop: 2023-02-02T19:25:00Z
unit_of_measurement: pcs
icon: mdi:storefront-outline

**Comment by Chouffy** [comment]
Hi @Rikkie80
This is a formatting done by Home Assistant, not by this module. Hence I cannot "fix" it here, as it's how HA manage numbers entities.
