### ISSUE TITLE
HA Automation trigger.to_state.attribute spacing instead of underscore

### ISSUE THREAD

**Issue by Florian14490** [Chouffy/home_assistant_tgtg#60]
Hello,

Thanks voor the good integration, works perfect !
I have one problem with trigger state.

Some state attributes have spacing instead of underscore between words.
That means that my automation not giving the correct info, it give me error.
I use folllowing : {{trigger.to_state.attributes.TGTG Price}} , its not working because of spacing between TGTG and Price.

Following is working: {{trigger.to_state.attributes.friendly_name}}, it has the underscore between friendly and name.

Example attributes of sensor:
Item ID: '75581'
Item URL: https://share.toogoodtogo.com/item/75581
TGTG Price: 4.99 EUR
Original value: 14.99 EUR
unit_of_measurement: pcs
icon: mdi:storefront-outline
friendly_name: TGTG 't Bakkershuys

The attributes with underscores are working but I cant get the attributes with spacing instead of underscore,=.

Is there a simple tip or trick to get them in my automation?
Example: {{ trigger.to_state.attributes.TGTG Price}}

Hope the here from you.
Already Thanks,

**Comment by tjorim** [comment]
From the documentation [here](https://www.home-assistant.io/docs/configuration/state_object).
When an attribute contains spaces, you can retrieve it like this:
`state_attr('sensor.tgtg_*', 'TGTG Price')`.

**Comment by Florian14490** [comment]
Thanks for reply, but not the right anwer.
I know that one what you say. But want to work in trigger.to_state. So how to get that work in trigger state?

I use in the automation trigger.to_state.attributes.

So wat you say is only to 1 specific sensor. I want that specific sensor as trigger.entity_id from what triggered the automation


state_attr('sensor.tgtg_*', 'TGTG Price').

Sensor.tgt*    has to be "trigger.entity_id.

But can not use it in the way you tells me.

Hope you have the answer
.
Thanks.

Verzonden vanaf Outlook voor Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by tjorim** [comment]
Agreed, reopening this issue! Although it's not in the developer docs, and I have other integrations that don't seem to use snake_case either, we could change/fix it here. Will be picked up when I'm back from holiday next week (or if anyone feels like giving it a shot).

**Comment by Florian14490** [comment]
@tjorim , yes offcourse.
Here is the automation I use. All trigger attributes data without the spacing (with underscores) are working correct and sending the right data of the triggers in my notify message. All trigger attributes with the spaces (without underscores) are not sending data of the triggers.




alias: TooGoodToGo Notification K + F (stock sensor)
description: TooGoodToGo Notify K + F (stock sensor)
trigger:
  - platform: state
    entity_id: >-
      sensor.tgtg_xxx,sensor.tgtg.xxx,sensor.tgtg.xxx,sensor.tgtg.xxx
    from: "0"
condition: []
action:
  - service: notify.mobile_app_tel_florian
    data:
      message: >-
        Beschikbaar: {{trigger.to_state.state}}, Voor: €   {{
        state_attr("trigger.entity_id", 'TGTG Price')}}, Start:
        {{trigger.to_state.attributes.Pickup start}}
      title: "{{trigger.to_state.attributes.friendly_name}}"
      data:
        clickAction: "{{trigger.to_state.attributes.Item URL}}"
        group: tgtg
        tag: "{{trigger.entity_id}}"
mode: parallel
max: 10

**Comment by tjorim** [comment]
@Florian14490 

Could you please try version 5.1.0? I released it as beta.
Please check the new attribute names and let me know what you think (and if it works as expected now).
In HACS you can look for tgtg, click the three dots in the corner and redownload:
![image](https://user-images.githubusercontent.com/1294876/219980853-2abcfae4-0e0a-4f75-a50c-b5b815e69517.png)

**Comment by Florian14490** [comment]
@tjorim 
Morning,
Just checked it while breakfast.
It perfects perfect now with the new attribute names.

Thank you verry much to put work in it.

Have a nice day
Grtz Florian
