### ISSUE TITLE
HA doesnt finish checking config before restart

### ISSUE THREAD

**Issue by euro2** [Chouffy/home_assistant_tgtg#75]
### System Health details

-

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/Chouffy/home_assistant_tgtg/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

after pasting in the config into a yaml file, HA doesnt finish checking the config before restart. The spinning icon never stops. Removing the config, it works as normal again. 

Logging into terminal and forcing a reboot. fingers crossed. 
EDIT: after forcing a reboot, the check config now works again. Maybe a full reboot was needed for the integration to settle?

- platform: tgtg
  email: "xxx@hotmail.com"
  access_token: "xxx"
  refresh_token: "xxx"
  user_id: "xxx"
  cookie: "xxx"
  scan_interval: 900

### Reproduction steps

1. Install TGTG via HACS
2. reboot
3. paste yaml config
...

### Debug logs

```text
-
```

### Diagnostics dump

-

**Comment by tjorim** [comment]
As edited in the issue, fixed after a reboot.
