### ISSUE TITLE
Connection pool is full/Captcha 403 error

### ISSUE THREAD

**Issue by Alfagek** [Chouffy/home_assistant_tgtg#76]
## System Information

version | core-2023.5.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.11
os_name | Linux
os_version | 6.1.25
arch | x86_64
timezone | Europe/Amsterdam
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.32.1
Stage | running
Available Repositories | 1350
Downloaded Repositories | 36
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.1
-- | --
update_channel | stable
supervisor_version | supervisor-2023.04.1
agent_version | 1.5.1
docker_version | 23.0.3
disk_total | 62.3 GB
disk_used | 21.6 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Home Assistant Google Drive Backup (0.110.4), Samba share (10.0.1), File editor (5.6.0), Terminal & SSH (9.7.0), Portainer (2.0.0), Mosquitto broker (6.2.1), WireGuard (0.8.0), AdGuard Home (4.8.6), TimescaleDB (2.1.1), Duck DNS (1.15.0), NGINX Home Assistant SSL proxy (3.4.2), SQLite Web (3.7.1), Studio Code Server (5.5.7), pgAdmin4 (2.1.1), Zigbee2MQTT (1.30.4-1), ESPHome (2023.4.4), Advanced SSH & Web Terminal (14.1.0), Frigate NVR Proxy (1.3), chrony (2.5.0), DSMR Reader (1.10.1), Vaultwarden (Bitwarden) (0.19.3)

</details>

<details><summary>Dashboards</summary>

dashboards | 4
-- | --
resources | 19
views | 21
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 27 april 2023 om 16:09
-- | --
current_recorder_run | 5 mei 2023 om 15:58
estimated_db_size | 1904.34 MiB
database_engine | sqlite
database_version | 3.40.1

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/Chouffy/home_assistant_tgtg/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

From 2023.5 i have this error in my log. 
Gladly I still get updates.

Working with HA in a VM in Proxmox

### Reproduction steps

1.
2.
3.
...

### Debug logs

```text
Deze fout is ontstaan door een aangepaste integratie.

Logger: urllib3.connectionpool
Source: custom_components/tgtg/sensor.py:189
Integration: tgtg (documentation, issues)
First occurred: 16:01:12 (80 occurrences)
Last logged: 16:22:12

Connection pool is full, discarding connection: apptoogoodtogo.com. Connection pool size: 10
```

**Comment by bartek75** [comment]
same here, and all entities are unavalaible

**Comment by tjorim** [comment]
Too good to go updated their API.
Release https://github.com/Chouffy/home_assistant_tgtg/releases/tag/5.2.0 should fix it.

**Comment by Alfagek** [comment]
Can confirm it’s working again. Thanks for the quick fix 👍🏻
