### ISSUE TITLE
Error 410 on first installation: "code":"ENTITY_DISABLED","message":"Entity ItemId(1234) is not active"

### ISSUE THREAD

**Issue by OldShaterhan** [Chouffy/home_assistant_tgtg#82]
## System Information

version | core-2023.7.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.4
os_name | Linux
os_version | 6.1.21-v8
arch | aarch64
timezone | Europe/Warsaw
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4716
Installed Version | 1.32.1
Stage | running
Available Repositories | 1273
Downloaded Repositories | 20

</details>

<details><summary>Airly</summary>

can_reach_server | ok
-- | --
requests_remaining | 7
requests_per_day | 100

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>GIOŚ</summary>

can_reach_server | pending
-- | --

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.3
-- | --
update_channel | stable
supervisor_version | supervisor-2023.07.1
agent_version | 1.5.1
docker_version | 23.0.6
disk_total | 116.5 GB
disk_used | 15.2 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Terminal & SSH (9.7.1), File editor (5.6.0), Node-RED (14.4.1), RPC Shutdown (2.4), Mosquitto broker (6.2.1), Spotify Connect (0.12.4), Grocy (0.19.1), Home Assistant Google Drive Backup (0.111.1), AdGuard Home (4.8.12), ESPHome (2023.7.0), Zigbee2MQTT (1.32.1-1), Matter Server (4.8.3), Music Assistant BETA (2.0.0b59)

</details>

<details><summary>Dashboards</summary>

dashboards | 7
-- | --
resources | 1
views | 19
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 23 maja 2023 12:11
-- | --
current_recorder_run | 23 lipca 2023 00:13
estimated_db_size | 1403.11 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | pending
-- | --

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/Chouffy/home_assistant_tgtg/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Integration cannot set up.

### Reproduction steps

1. Setup integration using data from tgtg.py script
2.
3.

Please note this is a brand new account.

### Debug logs

```text
Error while setting up tgtg platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 353, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tgtg/sensor.py", line 76, in setup_platform
    add_entities([TGTGSensor(each_item_id)])
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tgtg/sensor.py", line 96, in __init__
    self.update()
  File "/config/custom_components/tgtg/sensor.py", line 189, in update
    self.tgtg_answer = tgtg_client.get_item(item_id=self.item_id)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tgtg/__init__.py", line 287, in get_item
    raise TgtgAPIError(response.status_code, response.content)
tgtg.exceptions.TgtgAPIError: (410, b'{"errors":[{"code":"ENTITY_DISABLED","message":"Entity ItemId(1234) is not active"}]}')
```

**Comment by Chouffy** [comment]
Hi @OldShaterhan 
Did you add any favorites in your TGTG account? or did you specified some item id?

**Comment by Chouffy** [comment]
Closing this issue

**Comment by OldShaterhan** [comment]
Yes, I added optional property (I thought I have only token-generator code taken and exemplary removed).
