### ISSUE TITLE
Attribute 'item_price' is suddenly missing.

### ISSUE THREAD

**Issue by simphide** [Chouffy/home_assistant_tgtg#99]
## System Information

version | core-2023.12.4
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 5.4.0-169-generic
arch | x86_64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4817
Installed Version | 1.33.0
Stage | running
Available Repositories | 1367
Downloaded Repositories | 27

</details>

<details><summary>AccuWeather</summary>

can_reach_server | ok
-- | --
remaining_requests | 22

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 5
-- | --
resources | 17
views | 25
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | December 6, 2023 at 8:07 PM
-- | --
current_recorder_run | January 5, 2024 at 2:16 PM
estimated_db_size | 718.14 MiB
database_engine | mysql
database_version | 11.2.2

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/Chouffy/home_assistant_tgtg/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

I am getting an error, that no item price is returned anymore (also see the following screenshot):
![image](https://github.com/Chouffy/home_assistant_tgtg/assets/8183517/5cd15524-6839-4a63-b1f0-422f872a560b)

I have already genrated a new token and have restarted home assistant but the attribute is still missing.

### Reproduction steps

1. Just take a look at the sensors.

### Debug logs

```text
-
```

**Comment by simphide** [comment]
If I see it correctly the item_price gets determined from the field ["item"]["price_including_taxes"]["minor_units"]
```
if "price_including_taxes" in self.tgtg_answer["item"]:
                data[ATTR_PRICE] = (
                    str(
                        int(
                            self.tgtg_answer["item"]["price_including_taxes"][
                                "minor_units"
                            ]
                        )
                        / pow(
                            10,
                            int(
                                self.tgtg_answer["item"]["price_including_taxes"][
                                    "decimals"
                                ]
                            ),
                        )
                    )
                    + " "
                    + self.tgtg_answer["item"]["price_including_taxes"]["code"]
                )
```
Looking at the raw response from the TGTG library it should be ["item"]["item_price"]["minor_units"].

**Comment by tjorim** [comment]
Thank you for the information, the API must have changed. It could be helpful for people to also report upstream. Their readme still mentions `price_including_taxes` as well: https://github.com/ahivert/tgtg-python/blob/master/README.md.

**Comment by simphide** [comment]
I have created a pull request. Thank you for the fast feedback!
